/* This file was generated by blade */
extern "C" {
namespace binary_version {
extern const int kSvnInfoCount = 1;
extern const char* const kSvnInfo[1] = {"commit 98cbc2688de0697d21890dd34efb6c2712d8e390\n\
Author: rookieliao <rookieliao@angryhost>\n\
Date:   Sun Aug 21 21:30:25 2016 +0800\n\
\n\
    init\n\
"};
extern const char kBuildType[] = "release";
extern const char kBuildTime[] = "Sun Aug 21 23:33:45 2016";
extern const char kBuilderName[] = "rookieliao";
extern const char kHostName[] = "angryhost";
extern const char kCompiler[] = "GCC 4.9.2-10)";
}}
