/* This file was generated by blade */
extern "C" {
namespace binary_version {
extern const int kSvnInfoCount = 0;
extern const char* const kSvnInfo[0] = {};
extern const char kBuildType[] = "release";
extern const char kBuildTime[] = "Sun Aug 14 17:28:31 2016";
extern const char kBuilderName[] = "rookieliao";
extern const char kHostName[] = "angryhost";
extern const char kCompiler[] = "GCC 4.9.2-10)";
}}
