/* This file was generated by blade */
extern "C" {
namespace binary_version {
extern const int kSvnInfoCount = 1;
extern const char* const kSvnInfo[1] = {"commit 9235c18f588140b11d6df31d26fda5b72abab608\n\
Author: rookieliao <rookieliao@angryhost>\n\
Date:   Sun Aug 21 23:48:08 2016 +0800\n\
\n\
    get rpc compile correct\n\
"};
extern const char kBuildType[] = "release";
extern const char kBuildTime[] = "Sat Sep  3 15:17:36 2016";
extern const char kBuilderName[] = "rookieliao";
extern const char kHostName[] = "angryhost";
extern const char kCompiler[] = "GCC 4.9.2-10)";
}}
